version: '3'
services:
  bot:
    build: .
    command: python3 bot.py
    ports:
      - "5000:5000"
    environment:
      PROD: "true"
      BOT_TOKEN : "${BOT_TOKEN}"
      LOG_LEVEL: "${LOG_LEVEL}"
    volumes:
      - .:/code
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.10-alpine
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASS: test_pass
      POSTGRES_DB: karmabot
    volumes:
      - data:/var/lib/postgresql/data
      - ./start-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "5432:5432"
volumes:
  data: {}
